.PHONY: visual-log
visual-log:
	cat visualization/log | python visualization/visual.py

.PHONY: visual-log-without-denoising
visual-log-without-denoising:
	cat visualization/log-without-denoising | python visualization/visual.py

.PHONY: meta
meta:
	python openmind/meta.py