spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

jwt:
  issuer: ${JWT_ISSUER}
  expiration: ${JWT_EXPIRATION} # seconds

open-sas:
  server-addr: 127.0.0.1:10000