open-sas:
  publisher:
    group: WenZhou
    version:
      major: 1
      minor: 0
      patch: 0
    priority: 100
    port: 10001
  open-mind:
    host: 127.0.0.1
    port: 8080
    token: 76941044-34c4-4221-9dc1-daa871856fb3
